#if (defined NDEBUG)
    #define RAND_ENABLE_DEBUG_ASSERTS 0
#else
    #define RAND_ENABLE_DEBUG_ASSERTS 1
#endif

#define RAND_ENABLE_PROFILING 0

#define RAND_ENABLE_IMGUI 1

#define RAND_ENABLE_RENDERER2D_STATISTICS 1
